/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leancloud_api_web_function_jni_HelloWorld */

#ifndef _Included_com_leancloud_api_web_function_jni_HelloWorld
#define _Included_com_leancloud_api_web_function_jni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leancloud_api_web_function_jni_HelloWorld
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_leancloud_api_web_function_jni_HelloWorld_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_leancloud_api_web_function_jni_HelloWorld
 * Method:    testJni
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_leancloud_api_web_function_jni_HelloWorld_testJni
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
